# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.7

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/local/Cellar/cmake/3.7.1/bin/cmake

# The command to remove a file.
RM = /usr/local/Cellar/cmake/3.7.1/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /Users/Nicolas/Documents/workspace/ProgConcurente/Concurrence

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /Users/Nicolas/Documents/workspace/ProgConcurente/Concurrence

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/local/Cellar/cmake/3.7.1/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/local/Cellar/cmake/3.3.2/bin/ccmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/Nicolas/Documents/workspace/ProgConcurente/Concurrence/CMakeFiles /Users/Nicolas/Documents/workspace/ProgConcurente/Concurrence/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/Nicolas/Documents/workspace/ProgConcurente/Concurrence/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named Projet

# Build rule for target.
Projet: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 Projet
.PHONY : Projet

# fast build rule for target.
Projet/fast:
	$(MAKE) -f CMakeFiles/Projet.dir/build.make CMakeFiles/Projet.dir/build
.PHONY : Projet/fast

src/Character.o: src/Character.cpp.o

.PHONY : src/Character.o

# target to build an object file
src/Character.cpp.o:
	$(MAKE) -f CMakeFiles/Projet.dir/build.make CMakeFiles/Projet.dir/src/Character.cpp.o
.PHONY : src/Character.cpp.o

src/Character.i: src/Character.cpp.i

.PHONY : src/Character.i

# target to preprocess a source file
src/Character.cpp.i:
	$(MAKE) -f CMakeFiles/Projet.dir/build.make CMakeFiles/Projet.dir/src/Character.cpp.i
.PHONY : src/Character.cpp.i

src/Character.s: src/Character.cpp.s

.PHONY : src/Character.s

# target to generate assembly for a file
src/Character.cpp.s:
	$(MAKE) -f CMakeFiles/Projet.dir/build.make CMakeFiles/Projet.dir/src/Character.cpp.s
.PHONY : src/Character.cpp.s

src/Main.o: src/Main.cpp.o

.PHONY : src/Main.o

# target to build an object file
src/Main.cpp.o:
	$(MAKE) -f CMakeFiles/Projet.dir/build.make CMakeFiles/Projet.dir/src/Main.cpp.o
.PHONY : src/Main.cpp.o

src/Main.i: src/Main.cpp.i

.PHONY : src/Main.i

# target to preprocess a source file
src/Main.cpp.i:
	$(MAKE) -f CMakeFiles/Projet.dir/build.make CMakeFiles/Projet.dir/src/Main.cpp.i
.PHONY : src/Main.cpp.i

src/Main.s: src/Main.cpp.s

.PHONY : src/Main.s

# target to generate assembly for a file
src/Main.cpp.s:
	$(MAKE) -f CMakeFiles/Projet.dir/build.make CMakeFiles/Projet.dir/src/Main.cpp.s
.PHONY : src/Main.cpp.s

src/Motor.o: src/Motor.cpp.o

.PHONY : src/Motor.o

# target to build an object file
src/Motor.cpp.o:
	$(MAKE) -f CMakeFiles/Projet.dir/build.make CMakeFiles/Projet.dir/src/Motor.cpp.o
.PHONY : src/Motor.cpp.o

src/Motor.i: src/Motor.cpp.i

.PHONY : src/Motor.i

# target to preprocess a source file
src/Motor.cpp.i:
	$(MAKE) -f CMakeFiles/Projet.dir/build.make CMakeFiles/Projet.dir/src/Motor.cpp.i
.PHONY : src/Motor.cpp.i

src/Motor.s: src/Motor.cpp.s

.PHONY : src/Motor.s

# target to generate assembly for a file
src/Motor.cpp.s:
	$(MAKE) -f CMakeFiles/Projet.dir/build.make CMakeFiles/Projet.dir/src/Motor.cpp.s
.PHONY : src/Motor.cpp.s

src/OptionChecker.o: src/OptionChecker.cpp.o

.PHONY : src/OptionChecker.o

# target to build an object file
src/OptionChecker.cpp.o:
	$(MAKE) -f CMakeFiles/Projet.dir/build.make CMakeFiles/Projet.dir/src/OptionChecker.cpp.o
.PHONY : src/OptionChecker.cpp.o

src/OptionChecker.i: src/OptionChecker.cpp.i

.PHONY : src/OptionChecker.i

# target to preprocess a source file
src/OptionChecker.cpp.i:
	$(MAKE) -f CMakeFiles/Projet.dir/build.make CMakeFiles/Projet.dir/src/OptionChecker.cpp.i
.PHONY : src/OptionChecker.cpp.i

src/OptionChecker.s: src/OptionChecker.cpp.s

.PHONY : src/OptionChecker.s

# target to generate assembly for a file
src/OptionChecker.cpp.s:
	$(MAKE) -f CMakeFiles/Projet.dir/build.make CMakeFiles/Projet.dir/src/OptionChecker.cpp.s
.PHONY : src/OptionChecker.cpp.s

src/Plateau.o: src/Plateau.cpp.o

.PHONY : src/Plateau.o

# target to build an object file
src/Plateau.cpp.o:
	$(MAKE) -f CMakeFiles/Projet.dir/build.make CMakeFiles/Projet.dir/src/Plateau.cpp.o
.PHONY : src/Plateau.cpp.o

src/Plateau.i: src/Plateau.cpp.i

.PHONY : src/Plateau.i

# target to preprocess a source file
src/Plateau.cpp.i:
	$(MAKE) -f CMakeFiles/Projet.dir/build.make CMakeFiles/Projet.dir/src/Plateau.cpp.i
.PHONY : src/Plateau.cpp.i

src/Plateau.s: src/Plateau.cpp.s

.PHONY : src/Plateau.s

# target to generate assembly for a file
src/Plateau.cpp.s:
	$(MAKE) -f CMakeFiles/Projet.dir/build.make CMakeFiles/Projet.dir/src/Plateau.cpp.s
.PHONY : src/Plateau.cpp.s

src/Point.o: src/Point.cpp.o

.PHONY : src/Point.o

# target to build an object file
src/Point.cpp.o:
	$(MAKE) -f CMakeFiles/Projet.dir/build.make CMakeFiles/Projet.dir/src/Point.cpp.o
.PHONY : src/Point.cpp.o

src/Point.i: src/Point.cpp.i

.PHONY : src/Point.i

# target to preprocess a source file
src/Point.cpp.i:
	$(MAKE) -f CMakeFiles/Projet.dir/build.make CMakeFiles/Projet.dir/src/Point.cpp.i
.PHONY : src/Point.cpp.i

src/Point.s: src/Point.cpp.s

.PHONY : src/Point.s

# target to generate assembly for a file
src/Point.cpp.s:
	$(MAKE) -f CMakeFiles/Projet.dir/build.make CMakeFiles/Projet.dir/src/Point.cpp.s
.PHONY : src/Point.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... rebuild_cache"
	@echo "... edit_cache"
	@echo "... Projet"
	@echo "... src/Character.o"
	@echo "... src/Character.i"
	@echo "... src/Character.s"
	@echo "... src/Main.o"
	@echo "... src/Main.i"
	@echo "... src/Main.s"
	@echo "... src/Motor.o"
	@echo "... src/Motor.i"
	@echo "... src/Motor.s"
	@echo "... src/OptionChecker.o"
	@echo "... src/OptionChecker.i"
	@echo "... src/OptionChecker.s"
	@echo "... src/Plateau.o"
	@echo "... src/Plateau.i"
	@echo "... src/Plateau.s"
	@echo "... src/Point.o"
	@echo "... src/Point.i"
	@echo "... src/Point.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

